language: node_js
node_js: stable

# S: Build Lifecycle
before_install:
  - export TZ='Asia/Shanghai'

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - git clone https://${GH_REF} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/
  - cd ./public
  - git config user.name "CN-ZhangYue"
  - git config user.email "zhangyue3040@gmail.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/CN-ZhangYue/CN-ZhangYue.github.io.git
